services:
  athlete-first:
    container_name: athlete-first
    build:
      context: .
      target: DEV
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/app
      - ./scripts:/scripts
      - ./tests:/app/tests
      - ./pyproject.toml:/app/pyproject.toml
    env_file:
      - .env
    environment:
      - PORT=9000
      - DB_host=postgres
      - DB_user=${DB_user:-devuser}
      - DB_password=${DB_password:-devpass}
      - DB_name=${DB_name:-devdatabase}
    depends_on:
      - postgres

  postgres:
    image: postgres:17
    attach: false
    environment:
      - POSTGRES_USER=${DB_user:-devuser}
      - POSTGRES_PASSWORD=${DB_password:-devpass}
      - POSTGRES_DB=${DB_name:-devdatabase}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql

volumes:
  postgres_data:
