services:
  athlete-first-test:
    container_name: athlete-first-test
    build:
      context: .
      target: TEST
    ports:
      - "8001:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app
      - DATABASE_URL=postgresql://test_user:test_pass@db:5433/test_db
    depends_on:
      - pg-db-test

  pg-db-test:
    container_name: pg-db-test
    image: postgres:latest
    attach: false
    environment:
      - POSTGRES_USER=test_user
      - POSTGRES_PASSWORD=test_pass
      - POSTGRES_DB=test_db
    ports:
      - "5433:5432"
