services:
  athlete-first:
    container_name: athlete-first
    restart: unless-stopped
    build:
      context: .
      target: dev
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/app
      - ./scripts:/scripts
      - ./tests:/app/tests
      - ./pyproject.toml:/app/pyproject.toml
    env_file:
      - .env
    environment:
      - PORT=9000
      - AF_env=dev
      - DB_host=postgres
      - DB_user=${DB_user:-devuser}
      - DB_password=${DB_password:-devpass}
      - DB_name=${DB_name:-devdatabase}
    depends_on:
      - postgres

  postgres:
    image: postgres:17-alpine
    attach: false
    restart: unless-stopped
    environment:
      - POSTGRES_MULTIPLE_DATABASES=${DB_name:-devdatabase},test
      - POSTGRES_USER=${DB_user:-devuser}
      - POSTGRES_PASSWORD=${DB_password:-devpass}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/create-multiple-databases.sh:/docker-entrypoint-initdb.d/create-multiple-databases.sh

volumes:
  postgres_data:
